from libs import *

print('Gauss')
print('Mu: ')
gauss_mu = float(input())
print('Sigma: ')
gauss_sigma = float(input())
print('Size: ')
gauss_size = int(input())
gauss = np.random.normal(gauss_mu, gauss_sigma, gauss_size)
print(gauss)
s, p = normaltest(gauss)
print(p)
gauss_mean = np.mean(gauss)
print('mean: ', gauss_mean)
gauss_variance = np.var(gauss)
print('variance: ', gauss_variance)
plt.hist(gauss, bins=35)
plt.show()

print('Weibull ')
print('Alpha: ')
weibull_alpha = float(input())
print('Beta: ')
weibull_beta = float(input())
print('Size: ')
weibull_size = int(input())
weibull_rand = weibull_alpha * np.random.weibull(weibull_beta, weibull_size)
print(weibull_rand)
weibull_mean = np.mean(weibull_rand)
print('mean: ', weibull_mean)
weibull_variance = np.var(weibull_rand)
print('variance: ', weibull_variance)
plt.hist(weibull_rand, bins=35)
plt.show()

print('Rayleigh')
print('Scale: ')
rayleigh_scale = float(input())
print('Size: ')
rayleigh_size = int(input())
rayleigh_rand = np.random.rayleigh(rayleigh_scale, rayleigh_size)
print(rayleigh_rand)
rayleigh_mean = np.mean(rayleigh_rand)
print('mean: ', rayleigh_mean)
rayleigh_variance = np.var(rayleigh_rand)
print('variance: ', rayleigh_variance)
plt.hist(rayleigh_rand, bins=35)
plt.show()

print('Log-normal')
print('Mu: ')
lognormal_mu = float(input())
print('Sigma: ')
lognormal_sigma = float(input())
print('Size: ')
lognormal_size = int(input())
lognormal_rand = np.random.lognormal(lognormal_mu, lognormal_sigma, lognormal_size)
print(lognormal_rand)
lognormal_mean = np.mean(lognormal_rand)
print('mean: ', lognormal_mean)
lognormal_variance = np.var(lognormal_rand)
print('variance: ', lognormal_variance)
plt.hist(lognormal_rand, bins=35)
plt.show()

print('Cauchy')
print('Size: ')
cauchy_size = int(input())
cauchy_rand = np.random.standard_cauchy(cauchy_size)
print(cauchy_rand)
cauchy_mean = np.mean(cauchy_rand)
print('mean: ', cauchy_mean)
cauchy_variance = np.var(cauchy_rand)
print('variance: ', cauchy_variance)
plt.hist(cauchy_rand, bins=100)
plt.show()
